learning_rate: 0.3
optimizer: Adafactor
batch_size: 32
epochs: 3
# training_steps: 262144
training_steps: 100000
eval_steps: 500
save_steps: 500
warm_init: True
weight_decay: 0.00001
num_warmup_steps: 0
model_name: ../results/t5-base-qqp/best_model
# model_name: t5-base
# output_path: ../results
output_path: ../results/qqp
prompt_init_text: "Answer True or False: "
eval_strategy: steps
gradient_steps: 100
fp16: True
padding: max_length
truncation: True