learning_rate: 0.001
optimizer: AdamW
batch_size: 8
epochs: 1
warm_init: True
weight_decay: 0.0
num_warmup_steps: 0
model_name: google/t5-v1_1-base
output_path: ../results
prompt_init_text: Answer the question
eval_strategy: steps
gradient_steps: 100
fp16: True