learning_rate: 0.3
optimizer: Adafactor
batch_size: 32
epochs: 3
training_steps: 100000
eval_steps: 500
save_steps: 500
warm_init: True
weight_decay: 0.00001
num_warmup_steps: 0
model_name: bigscience/bloomz-560m
output_path: ../results
language: english
# output_path: ../results/qqp
prompt_init_text: "Classify if the following text is checkworthy or not:"
eval_strategy: steps
gradient_steps: 100
fp16: True
padding: max_length
truncation: True
init_type: text
num_virtual_tokens: 20